[package]
name = "harness"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", default-features = false, features = [
  "html_reports",
] }
verq = { workspace = true }


[build-dependencies]
cc = { version = "1.1.14", features = ["parallel"] }
